version: '3.8'
services:
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mutant?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: oscarperiferia
      SPRING_DATASOURCE_PASSWORD: 8kDD#u3tQhNniv&
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mutant
      MYSQL_USER: oscarperiferia
      MYSQL_PASSWORD: 8kDD#u3tQhNniv&
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
