name: Java Maven Automated Tests with Coverage Check

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Generate coverage report with JaCoCo
        run: mvn jacoco:report

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Print JaCoCo report
        run: cat target/site/jacoco/jacoco.xml

      - name: Check coverage threshold
        id: coverage
        run: |
          # Extract the coverage data from the JaCoCo report using xmllint
          COVERED=$(xmllint --xpath "string(//counter[@type='INSTRUCTION']/@covered)" target/site/jacoco/jacoco.xml)
          MISSED=$(xmllint --xpath "string(//counter[@type='INSTRUCTION']/@missed)" target/site/jacoco/jacoco.xml)
          
          if [ -z "$COVERED" ] || [ -z "$MISSED" ]; then
            echo "Coverage data not found in JaCoCo report"
            exit 1
          fi

          TOTAL=$((COVERED + MISSED))
          COVERAGE_PERCENT=$((100 * COVERED / TOTAL))
          
          echo "Coverage Percentage: $COVERAGE_PERCENT%"

          # Check if coverage is above the threshold
          if [ "$COVERAGE_PERCENT" -lt 50 ]; then
            echo "Coverage is below 50%. Current coverage: $COVERAGE_PERCENT%"
            exit 1
          else
            echo "Coverage is acceptable. Current coverage: $COVERAGE_PERCENT%"
          fi
