name: Java Maven Automated Tests with Coverage Check

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Generate coverage report with JaCoCo
        run: mvn jacoco:report

      - name: Print JaCoCo report
        run: cat target/site/jacoco/jacoco.xml